# Generated by Django 4.2 on 2023-05-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sutdent_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('education', models.IntegerField(max_length=50)),
                ('Image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
