# Generated by Django 4.2 on 2023-05-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sutdent_info',
            name='education',
            field=models.CharField(choices=[('MBA', 'MBA'), ('CS', 'CS'), ('BS', 'BS')], max_length=50),
        ),
    ]
