# Generated by Django 4.2 on 2023-05-04 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_sutdent_info_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sutdent_info',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
