# Generated by Django 4.2 on 2023-06-17 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_sutdent_info_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester1_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.IntegerField(default=0)),
                ('english', models.IntegerField(default=0)),
                ('dbms', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.sutdent_info')),
            ],
        ),
    ]
