# Generated by Django 4.2 on 2023-06-21 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_semester1_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester1_marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='sms.sutdent_info'),
        ),
    ]
